### ISSUE TITLE
Implement privacy features

### ISSUE THREAD

**Issue by pcschreiber1** [GFA-DIU/GFA-DIU.github.io#18]
Implement privacy features:
 - [Mkdocs: Ensuring data privacy](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=)

**Comment by fretchen** [comment]
Hi @pcschreiber1 as far as I understand it there is no need for the consent forms as we are not using any cookies.

**Comment by fretchen** [comment]
Closed in 080fce185f1d6285395a27d70f6f5187c58b3c29
